on:
  push:
    paths:
      - .github/workflows/main.yml
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 148.72.26.110
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: '/test/'

    - name: Call API
      run: |
        export BASE_URL="https://restaurant60-be-dev-xtpocjmkpa-uw.a.run.app/app-url-update"
        export type="Website"
        export restaurant_id="645"
        export apk_name2="${{ env.apk_name }}"
        export company_name="${{ env.Company_Name }}"
        export email="${{ env.email }}"
        export url="${{ env.apk_name.'tissatech.in' }}"
        export API_URL="$BASE_URL/?url=$url&type=$type&restaurant_id=$restaurant_id&app_name=$apk_name2&emails=$email&compony_name=$company_name"
        # echo "Uploading APK: $API_URL"
        # response=$(curl -X GET $API_URL)
        # echo "API Response: $response"
        echo url
